---
- name: Configure Kubernetes nodes
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common

- name: Configure Kubernetes master nodes
  hosts: k8s_masters
  become: true
  roles:
    - master

- name: Configure Kubernetes worker nodes
  hosts: k8s_workers
  become: true
  roles:
    - worker

- name: Verify configuration
  hosts: all
  become: true
  tasks:
    - name: Verify hostname is set correctly
      debug:
        msg: "Current hostname: {{ ansible_hostname }}"

    - name: Verify /etc/hosts configuration
      command: cat /etc/hosts
      register: hosts_file
      changed_when: false

    - name: Display /etc/hosts content
      debug:
        msg: "{{ hosts_file.stdout_lines }}"

- name: Reboot all servers
  hosts: all
  become: true
  tags: reboot
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      ignore_errors: yes

    - name: Notify about pending reboot
      debug:
        msg: "Server {{ inventory_hostname }} will be rebooted to apply all changes"

    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible for Kubernetes setup"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      register: reboot_result

    - name: Display reboot status
      debug:
        var: reboot_result
        verbosity: 1

    - name: Verify system is running after reboot
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Get uptime after reboot
      shell: uptime
      register: uptime
      changed_when: false

    - name: Display uptime
      debug:
        msg: "{{ inventory_hostname }} is up and running: {{ uptime.stdout }}"
